const $ = (id) => document.getElementById(id)
const modal = $('noteTakerModal')
let stream, recorder, recognition, audioContext, analyser, raf, timer, startedAt, pausedMs = 0, pauseAt, segments = [], interim = '', state = 'idle', sessionId
const Speech = window.SpeechRecognition || window.webkitSpeechRecognition

function formatTime(ms) { const s = Math.floor(ms / 1000); return [Math.floor(s / 3600), Math.floor(s / 60) % 60, s % 60].map((n) => String(n).padStart(2, '0')).join(':') }
function elapsed() { return startedAt ? formatTime(Date.now() - startedAt - pausedMs - (pauseAt ? Date.now() - pauseAt : 0)) : '00:00:00' }
function setStatus(text, connection = '') { $('noteTakerStatus').textContent = text; $('noteTakerConnection').textContent = connection }
function render() { const root = $('noteTakerTranscript'); root.innerHTML = segments.map((s) => `<p class="note-segment"><time>${s.time}</time><span>${escapeHtml(s.text)}</span></p>`).join('') + (interim ? `<p class="note-segment interim"><time></time><span>${escapeHtml(interim)}</span></p>` : '') || '<p class="note-taker-empty">Your transcript will appear here as people speak.</p>' }
function escapeHtml(v) { return v.replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])) }
function open() { modal.hidden = false; document.body.classList.add('note-taker-open'); $('noteTakerSetup').hidden = false; $('noteTakerLive').hidden = true; $('noteTakerComplete').hidden = true; $('noteTakerMeetingTitle').focus() }
function close() { if (state === 'recording' || state === 'paused') { if (!confirm('Close Note Taker? Your current recording will remain open.')) return; } modal.hidden = true; document.body.classList.remove('note-taker-open') }
async function start() {
  if (!navigator.mediaDevices?.getUserMedia) return setStatus('Microphone unavailable', 'Use Cognita in a secure browser context (HTTPS).')
  state = 'requesting-permission'; setStatus('Requesting microphone', 'Allow microphone access to begin')
  try { stream = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true, noiseSuppression: true, autoGainControl: true } }) } catch (e) { state = 'error'; return setStatus('Microphone access is required', e.name === 'NotAllowedError' ? 'Enable microphone permission in your browser, then try again.' : 'No usable microphone was found.') }
  sessionId = crypto.randomUUID(); segments = []; interim = ''; pausedMs = 0; startedAt = Date.now(); $('noteTakerSetup').hidden = true; $('noteTakerLive').hidden = false; state = 'recording'; setStatus('Recording', Speech ? 'Browser fallback ready' : 'Audio is being preserved locally');
  timer = setInterval(() => $('noteTakerTimer').textContent = elapsed(), 250)
  if (window.MediaRecorder) { recorder = new MediaRecorder(stream); recorder.ondataavailable = (e) => { if (e.data.size) window.dispatchEvent(new CustomEvent('cognita:note-audio', { detail: { sessionId, chunk: e.data } })) }; recorder.start(1000) }
  try { audioContext = new AudioContext(); analyser = audioContext.createAnalyser(); audioContext.createMediaStreamSource(stream).connect(analyser); drawLevel() } catch {}
  if (Speech) startRecognition(); else setStatus('Recording', 'Live transcription unavailable; audio is being preserved')
}
function startRecognition() { recognition = new Speech(); recognition.continuous = true; recognition.interimResults = true; recognition.lang = $('noteTakerLanguage').value === 'auto' ? 'en-NG' : $('noteTakerLanguage').value; recognition.onresult = (e) => { interim = ''; for (let i = e.resultIndex; i < e.results.length; i++) { const text = e.results[i][0].transcript.trim(); if (e.results[i].isFinal && text) { const last = segments[segments.length - 1]; if (!last || last.text !== text) segments.push({ id: crypto.randomUUID(), time: elapsed(), text }) } else interim += text + ' ' } render() }; recognition.onerror = () => setStatus('Degraded', 'Live transcription interrupted; recording is preserved'); recognition.onend = () => { if (state === 'recording') { try { recognition.start() } catch {} } }; recognition.start() }
function drawLevel() { if (!analyser || state !== 'recording') return; const data = new Uint8Array(analyser.frequencyBinCount); analyser.getByteTimeDomainData(data); const level = data.reduce((sum, n) => sum + Math.abs(n - 128), 0) / data.length; $('noteTakerPulse').style.setProperty('--level', Math.min(1, level / 32)); raf = requestAnimationFrame(drawLevel) }
function pause() { if (state === 'recording') { state = 'paused'; pauseAt = Date.now(); stream?.getTracks().forEach((t) => t.enabled = false); recognition?.stop(); $('noteTakerPause').innerHTML = '<i class="ph ph-play"></i> Resume'; setStatus('Paused', 'Audio capture is paused'); cancelAnimationFrame(raf) } else if (state === 'paused') { pausedMs += Date.now() - pauseAt; pauseAt = 0; state = 'recording'; stream?.getTracks().forEach((t) => t.enabled = true); if (recognition) try { recognition.start() } catch {} $('noteTakerPause').innerHTML = '<i class="ph ph-pause"></i> Pause'; setStatus('Recording', 'Live transcription active'); drawLevel() } }
function finish() { if (!segments.length && !interim) return stopNow(); if (confirm('Finish note? Your live transcript will be finalized.')) stopNow() }
function stopNow() { state = 'completed'; recognition?.stop(); recorder?.stop(); stream?.getTracks().forEach((t) => t.stop()); audioContext?.close(); clearInterval(timer); cancelAnimationFrame(raf); if (interim) { segments.push({ id: crypto.randomUUID(), time: elapsed(), text: interim.trim() }); interim = '' } const text = segments.map((s) => `[${s.time}] ${s.text}`).join('\n\n'); $('noteTakerEditor').value = text; $('noteTakerCompleteTitle').textContent = $('noteTakerMeetingTitle').value.trim() || 'Meeting Notes'; $('noteTakerMeta').textContent = `${new Date().toLocaleDateString()} · ${elapsed()} · ${$('noteTakerLanguage').selectedOptions[0].text}`; $('noteTakerLive').hidden = true; $('noteTakerComplete').hidden = false }
$('noteTakerStart').addEventListener('click', start); $('noteTakerPause').addEventListener('click', pause); $('noteTakerStop').addEventListener('click', finish); $('noteTakerClose').addEventListener('click', close); $('noteTakerCopy').addEventListener('click', async () => { await navigator.clipboard.writeText($('noteTakerEditor').value); $('noteTakerCopy').textContent = 'Copied' }); $('noteTakerDownload').addEventListener('click', () => { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([$('noteTakerEditor').value], { type: 'text/plain' })); a.download = `${$('noteTakerCompleteTitle').textContent || 'meeting-notes'}.txt`; a.click(); URL.revokeObjectURL(a.href) }); $('noteTakerEdit').addEventListener('click', () => $('noteTakerEditor').focus()); $('noteTakerAsk').addEventListener('click', () => { const input = $('composerInput'); input.value = `Please help me process these meeting notes:\n\n${$('noteTakerEditor').value}`; input.dispatchEvent(new Event('input', { bubbles: true })); close(); input.focus() }); window.addEventListener('cognita:open-note-taker', open); window.addEventListener('online', () => { if (state === 'recording') setStatus('Recording', 'Connection restored') }); window.addEventListener('offline', () => { if (state === 'recording') setStatus('Degraded', 'Offline — audio is being preserved locally') }); window.addEventListener('beforeunload', (e) => { if (state === 'recording') { e.preventDefault(); e.returnValue = '' } });
