# Renders every Learna diagram to PNG (and keeps the SVG source), then writes learna/visuals.js,
# the single place where the courses look up an image, its description and its tappable hotspots.
# Run from the repo root:  python3 scripts/learna-visuals/build.py
import json, os, sys, io
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
from diagrams_js import ALL as JS
from diagrams_speaking import ALL as SP
from playwright.sync_api import sync_playwright
from PIL import Image

def camel(k):
    p = k.split('-'); return p[0] + ''.join(x.capitalize() for x in p[1:])

entries = JS + SP
meta = {}
os.makedirs(os.path.join(ROOT, 'assets/learna/src'), exist_ok=True)
with sync_playwright() as pw:
    b = pw.chromium.launch(); pg = b.new_page(viewport={'width': 1200, 'height': 675})
    for key, rel, alt, cap, fn in entries:
        c = fn(); svg = c.svg()
        open(os.path.join(ROOT, 'assets/learna/src', rel.replace('/', '-') + '.svg'), 'w', encoding='utf-8').write(svg)
        pg.set_content('<html><body style="margin:0">' + svg + '</body></html>')
        raw = pg.screenshot(type='png', clip={'x': 0, 'y': 0, 'width': 1200, 'height': 675})
        im = Image.open(io.BytesIO(raw)).convert('RGB').quantize(colors=96, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
        out = os.path.join(ROOT, 'assets/learna', rel + '.png')
        os.makedirs(os.path.dirname(out), exist_ok=True); im.save(out, optimize=True)
        meta[key] = {'src': '/assets/learna/' + rel + '.png', 'alt': alt, 'caption': cap, 'hotspots': c.hot}
        print(key, os.path.getsize(out) // 1024, 'KB', len(c.hot), 'hotspots')
    b.close()
js = ['// learna/visuals.js', '// GENERATED by scripts/learna-visuals/build.py. Do not edit by hand: change the diagram script and run it again.',
      "// Each entry is a ready-made visual() block for a teaching step. Hotspot x and y are percentages of the picture.", '', 'export const VIS = {']
for k, v in meta.items(): js.append('  ' + json.dumps(camel(k)) + ': ' + json.dumps(v, ensure_ascii=False) + ',')
js.append('};'); js.append('')
open(os.path.join(ROOT, 'learna/visuals.js'), 'w', encoding='utf-8').write('\n'.join(js))
print('wrote learna/visuals.js with', len(meta), 'visuals')
