// reminders/push-vapid.js
// Web Push from scratch on the Web Crypto API — no `web-push` npm package,
// since that package assumes Node's `crypto` module, which Workers doesn't
// provide. Two independent pieces:
//
//   1. VAPID: an ES256-signed JWT that proves to the push service which
//      application server is sending (RFC 8292).
//   2. Payload encryption: RFC 8291 ("aes128gcm" content coding, RFC 8188),
//      verified byte-for-byte against the worked example in RFC 8291
//      Appendix A — see reminders/push-vapid.test.js.
//
// Nothing here is specific to any one push service (FCM, Mozilla's
// autopush, etc.) — the same VAPID header and the same encrypted body work
// for all of them, which is the whole point of the standard.

function b64urlToBytes(str) {
  const b64 = String(str).replace(/-/g, '+').replace(/_/g, '/');
  const pad = b64.length % 4 === 0 ? '' : '='.repeat(4 - (b64.length % 4));
  const raw = atob(b64 + pad);
  const arr = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) arr[i] = raw.charCodeAt(i);
  return arr;
}

function bytesToB64url(bytes) {
  let binary = '';
  const arr = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  for (let i = 0; i < arr.length; i++) binary += String.fromCharCode(arr[i]);
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function utf8(s) {
  return new TextEncoder().encode(s);
}

function concatBytes(...parts) {
  const arrs = parts.map((p) => (p instanceof Uint8Array ? p : new Uint8Array(p)));
  const total = arrs.reduce((n, a) => n + a.length, 0);
  const out = new Uint8Array(total);
  let off = 0;
  for (const a of arrs) {
    out.set(a, off);
    off += a.length;
  }
  return out;
}

/**
 * Rebuilds the WebCrypto JWK for our VAPID private key from the parts
 * generated by pwa/vapid-keygen.html (see that file for the export side).
 * `env.VAPID_PRIVATE_KEY` holds the full JWK JSON as a Worker secret.
 */
async function _importVapidPrivateKey(env) {
  if (!env.VAPID_PRIVATE_KEY) {
    throw new Error('Server misconfiguration: VAPID_PRIVATE_KEY not set.');
  }
  let jwk;
  try {
    jwk = JSON.parse(env.VAPID_PRIVATE_KEY);
  } catch (_) {
    throw new Error('Server misconfiguration: VAPID_PRIVATE_KEY is not valid JSON.');
  }
  return crypto.subtle.importKey('jwk', jwk, { name: 'ECDSA', namedCurve: 'P-256' }, false, ['sign']);
}

const _vapidJwtCache = new Map(); // audience -> { jwt, expiry }

/**
 * Builds the "Authorization: vapid t=<jwt>, k=<publicKey>" header value for
 * one push service origin (the "aud" claim MUST be that origin exactly —
 * RFC 8292 — so this is cached per-audience, not globally).
 */
export async function buildVapidAuthHeader(env, audienceOrigin) {
  const cached = _vapidJwtCache.get(audienceOrigin);
  const now = Math.floor(Date.now() / 1000);
  if (cached && cached.expiry > now + 60) {
    return 'vapid t=' + cached.jwt + ', k=' + env.VAPID_PUBLIC_KEY;
  }

  if (!env.VAPID_PUBLIC_KEY) {
    throw new Error('Server misconfiguration: VAPID_PUBLIC_KEY not set.');
  }
  if (!env.VAPID_SUBJECT) {
    throw new Error('Server misconfiguration: VAPID_SUBJECT not set.');
  }

  const privateKey = await _importVapidPrivateKey(env);
  const exp = now + 12 * 3600; // 12h, well inside RFC 8292's "no more than 24h" guidance

  const header = bytesToB64url(utf8(JSON.stringify({ typ: 'JWT', alg: 'ES256' })));
  const payload = bytesToB64url(
    utf8(JSON.stringify({ aud: audienceOrigin, exp, sub: env.VAPID_SUBJECT }))
  );
  const signInput = header + '.' + payload;

  // WebCrypto's ECDSA signatures are already the raw (r || s) IEEE P1363
  // form JWS expects — no DER-to-raw conversion needed, unlike most
  // general-purpose crypto libraries.
  const sigBits = await crypto.subtle.sign(
    { name: 'ECDSA', hash: 'SHA-256' },
    privateKey,
    utf8(signInput)
  );
  const jwt = signInput + '.' + bytesToB64url(sigBits);

  _vapidJwtCache.set(audienceOrigin, { jwt, expiry: exp });
  if (_vapidJwtCache.size > 20) _vapidJwtCache.clear(); // small orgs, small cache; avoid unbounded growth

  return 'vapid t=' + jwt + ', k=' + env.VAPID_PUBLIC_KEY;
}

/**
 * Encrypts `plaintext` (a UTF-8 string, kept short — push services cap the
 * body around 4KB) for one subscription, per RFC 8291. Returns raw bytes
 * ready to POST as the push message body.
 */
export async function encryptPushPayload(subscription, plaintext) {
  const uaPublicRaw = b64urlToBytes(subscription.p256dh);
  const authSecret = b64urlToBytes(subscription.auth);
  if (uaPublicRaw.length !== 65 || uaPublicRaw[0] !== 0x04) {
    throw new Error('Subscription public key is not a valid uncompressed P-256 point.');
  }
  if (authSecret.length !== 16) {
    throw new Error('Subscription auth secret must be 16 bytes.');
  }

  const asKeyPair = await crypto.subtle.generateKey({ name: 'ECDH', namedCurve: 'P-256' }, true, [
    'deriveBits',
  ]);
  const asPublicRaw = new Uint8Array(await crypto.subtle.exportKey('raw', asKeyPair.publicKey));

  const uaPublicKey = await crypto.subtle.importKey(
    'raw',
    uaPublicRaw,
    { name: 'ECDH', namedCurve: 'P-256' },
    false,
    []
  );
  const ecdhSecretBits = await crypto.subtle.deriveBits(
    { name: 'ECDH', public: uaPublicKey },
    asKeyPair.privateKey,
    256
  );
  const ecdhSecret = new Uint8Array(ecdhSecretBits);

  // IKM = HKDF(salt=auth_secret, ikm=ecdh_secret, info=key_info, L=32)  — RFC 8291 §3.3
  const keyInfo = concatBytes(utf8('WebPush: info'), new Uint8Array([0]), uaPublicRaw, asPublicRaw);
  const ecdhKeyMaterial = await crypto.subtle.importKey('raw', ecdhSecret, 'HKDF', false, [
    'deriveBits',
  ]);
  const ikmBits = await crypto.subtle.deriveBits(
    { name: 'HKDF', hash: 'SHA-256', salt: authSecret, info: keyInfo },
    ecdhKeyMaterial,
    256
  );
  const ikm = new Uint8Array(ikmBits);

  const salt = crypto.getRandomValues(new Uint8Array(16));

  // CEK / NONCE = HKDF(salt, ikm, info=<label>, L)  — RFC 8188 §2.1 via RFC 8291 §3.4
  const ikmKeyMaterial = await crypto.subtle.importKey('raw', ikm, 'HKDF', false, ['deriveBits']);
  const cekInfo = concatBytes(utf8('Content-Encoding: aes128gcm'), new Uint8Array([0]));
  const nonceInfo = concatBytes(utf8('Content-Encoding: nonce'), new Uint8Array([0]));
  const cekBits = await crypto.subtle.deriveBits(
    { name: 'HKDF', hash: 'SHA-256', salt, info: cekInfo },
    ikmKeyMaterial,
    128
  );
  const nonceBits = await crypto.subtle.deriveBits(
    { name: 'HKDF', hash: 'SHA-256', salt, info: nonceInfo },
    ikmKeyMaterial,
    96
  );
  const cek = new Uint8Array(cekBits);
  const nonce = new Uint8Array(nonceBits);

  // Single-record aes128gcm body: plaintext + 0x02 padding delimiter, no
  // further padding (RFC 8291 §4 — we always encrypt in one record).
  const paddedPlaintext = concatBytes(utf8(plaintext), new Uint8Array([2]));

  const aesKey = await crypto.subtle.importKey('raw', cek, { name: 'AES-GCM' }, false, ['encrypt']);
  const ciphertextBits = await crypto.subtle.encrypt({ name: 'AES-GCM', iv: nonce }, aesKey, paddedPlaintext);
  const ciphertext = new Uint8Array(ciphertextBits);

  // Header per RFC 8188 §2.1: salt(16) || rs(4, big-endian uint32) || idlen(1) || keyid(as_public, 65).
  // rs must exceed plaintext+delimiter+tag; push bodies here are always
  // small, so a fixed generous value (matching the RFC's own example) is
  // simpler than computing an exact minimum.
  const rs = new Uint8Array(4);
  new DataView(rs.buffer).setUint32(0, 4096);
  const header = concatBytes(salt, rs, new Uint8Array([asPublicRaw.length]), asPublicRaw);

  return concatBytes(header, ciphertext);
}

/**
 * Sends one Web Push message. Returns { ok, status, gone } — `gone` is
 * true on 404/410, meaning the caller should delete the subscription.
 */
export async function sendWebPush(env, subscription, payloadObj, { ttlSeconds = 86400 } = {}) {
  const endpointUrl = new URL(subscription.endpoint);
  const audience = endpointUrl.origin;

  const [authHeader, body] = await Promise.all([
    buildVapidAuthHeader(env, audience),
    encryptPushPayload(subscription, JSON.stringify(payloadObj)),
  ]);

  const res = await fetch(subscription.endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/octet-stream',
      'Content-Encoding': 'aes128gcm',
      TTL: String(ttlSeconds),
      Authorization: authHeader,
    },
    body,
  });

  if (res.status === 404 || res.status === 410) {
    return { ok: false, status: res.status, gone: true };
  }
  if (!res.ok) {
    return { ok: false, status: res.status, gone: false };
  }
  return { ok: true, status: res.status, gone: false };
}

export const _internal = { b64urlToBytes, bytesToB64url, concatBytes, utf8 };
